### ISSUE TITLE
Prior Art

### ISSUE THREAD

**Issue by bcomnes** [moose-team/rich-message#1]
There has been a bit of plaintext projects in indieweb projects.  Interested in prior art examples?

**Comment by ungoldman** [comment]
:v: sure why not :+1:

**Comment by max-mapper** [comment]
especially if they are modules on npm that are good

**Comment by bcomnes** [comment]
I think https://www.npmjs.com/package/text-autolinker is based on https://github.com/tantek/cassis/blob/master/cassis.js#L1166

I'll try to find some others.  Most of these look like they are actually for blogs, so I'm not exactly sure how reusable they will be here
